### ISSUE TITLE
ARNL packages for different architecture

### ISSUE THREAD

**Issue by Bleky1** [ITVRoC/SeekurJr#2]
Do you have i386 versions of arnl-base and libarnl besides amd64?

**Comment by AndreCid** [comment]
Hello! I will search if we have for you as soon as possible!

**Comment by AndreCid** [comment]
All we have are the files from Adept MobileRobots CD (https://github.com/ITVRoC/SeekurJr/tree/master/Seekur_CDs/CD-Aria).

**Comment by Bleky1** [comment]
Alright, thank you for searching.
